fix: add rgpd tests

diff --git a/.github/workflows/declaration-rgpd.yml b/.github/workflows/declaration-rgpd.yml
--- a/.github/workflows/declaration-rgpd.yml
+++ b/.github/workflows/declaration-rgpd.yml
@@ -2,13 +2,13 @@ on:
   push:
     branches: ["*"]
     paths:
-      - declaration-rgpd
+      - declaration-rgpd/*
       - .github/workflows/declaration-rgpd.yml
 
   pull_request:
     branches: ["*"]
     paths:
-      - declaration-rgpd
+      - declaration-rgpd/*
       - .github/workflows/declaration-rgpd.yml
 
 name: Test declaration-rgpd
@@ -35,9 +35,19 @@ jobs:
           url: https://labonnealternance.apprentissage.beta.gouv.fr
           thirdparties: '{"trackers":[{"type":"unknown","url":"https://plausible.io/js/plausible.local.outbound-links.js"},{"type":"unknown","url":"https://plausible.io/api/event"}],"cookies":[],"headers":{"cache-control":"s-maxage=31536000,stale-while-revalidate","content-encoding":"gzip","content-type":"text/html;charset=utf-8","date":"Tue,06Sep202210:00:11GMT","etag":"\"34252-Rg+tkwu+qSjfdl/R14jfhbBq4KA\"","server":"nginx","vary":"Accept-Encoding","x-nextjs-cache":"HIT","x-powered-by":"Next.js"}}'
           output: rgpd.json
-
       - shell: bash
         run: |
           ls -la
           cat rgpd.json
           [[ $(cat rgpd.json | jq '.[0].score') -eq "3" ]] || (echo "Error: Should score 3" && exit 1)
+      - uses: ./declaration-rgpd
+        with:
+          url: https://conseillers-entreprises.service-public.fr
+          thirdparties: '{"trackers":[],"cookies":[],"headers":{"cache-control":"s-maxage=31536000,stale-while-revalidate","content-encoding":"gzip","content-type":"text/html;charset=utf-8","date":"Tue,06Sep202210:00:11GMT","etag":"\"34252-Rg+tkwu+qSjfdl/R14jfhbBq4KA\"","server":"nginx","vary":"Accept-Encoding","x-nextjs-cache":"HIT","x-powered-by":"Next.js"}}'
+          output: rgpd2.json
+
+      - shell: bash
+        run: |
+          ls -la
+          cat rgpd2.json
+          [[ $(cat rgpd2.json | jq '.[0].score') -eq "3" ]] || (echo "Error: Should score 3" && exit 1)
